// components/home/AiSnapshotOfDay.tsx
import { Section, Card, Badge } from "@/components/ui";

const aiHighlights = [
  {
    id: 1,
    insight: "AI Tools apps grew fastest in Southeast Asia (+22%) driven by new face filter launches.",
    category: "Regional Growth",
    icon: "🌏",
  },
  {
    id: 2,
    insight: "Games remain dominant globally, contributing 47% of total installs this week.",
    category: "Market Share",
    icon: "🎮",
  },
  {
    id: 3,
    insight: "Fintech apps show rising retention — 18% higher user reactivation this quarter.",
    category: "User Behavior",
    icon: "💰",
  },
];

export function AiSnapshotOfDay() {
  return (
    <Section
      title="AI Snapshot of the Day"
      description="Real-time insights generated by AppCortex AI every 3 hours"
    >
      <div className="grid gap-4 md:grid-cols-3">
        {aiHighlights.map((highlight) => (
          <Card
            key={highlight.id}
            hover
            className="p-5 bg-gradient-to-br from-slate-900/80 to-slate-900/40"
          >
            <div className="flex items-start gap-3 mb-3">
              <span className="text-3xl" role="img" aria-label="icon">
                {highlight.icon}
              </span>
              <Badge variant="cyan" className="text-[9px]">
                {highlight.category}
              </Badge>
            </div>
            <p className="text-sm text-slate-200 leading-relaxed">
              {highlight.insight}
            </p>
            <div className="mt-4 flex items-center gap-2 text-xs text-cyan-400">
              <svg
                className="h-3.5 w-3.5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 10V3L4 14h7v7l9-11h-7z"
                />
              </svg>
              <span>AI-Generated</span>
            </div>
          </Card>
        ))}
      </div>
      <div className="mt-4 text-center">
        <a
          href="/insights/ai-market"
          className="text-sm text-cyan-400 hover:text-cyan-300 transition-colors"
        >
          View Full AI Insights →
        </a>
      </div>
    </Section>
  );
}

