export function AiSnapshotOfDay() {
  // This would be generated daily by your AI system
  const snapshot = {
    title: "AI Snapshot of the Day",
    insight: "Today, Health & Fitness apps are seeing an unusual spike in downloads in MENA and Southeast Asia. Subscription-based meditation and sleep apps lead the growth.",
    tags: ["#Health & Fitness", "#MENA", "#Subscription"],
    generatedAt: new Date().toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    }),
    chartData: [
      { label: "Yesterday", value: 65 },
      { label: "Today", value: 100 },
    ],
  };

  return (
    <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
      <div className="relative bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-950/30 dark:to-purple-950/30 border border-indigo-200 dark:border-indigo-800/50 rounded-2xl p-6 sm:p-8 overflow-hidden">
        {/* Background Pattern */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-indigo-400/10 to-purple-400/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative">
          {/* Header */}
          <div className="flex items-start gap-3 mb-4">
            <div className="flex-shrink-0 h-10 w-10 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg">
              <svg className="h-5 w-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <div>
              <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-slate-50 mb-1">
                {snapshot.title}
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Daily market intelligence from AppCortex AI
              </p>
            </div>
          </div>

          {/* Main Content Grid */}
          <div className="grid lg:grid-cols-[1fr,auto] gap-6">
            {/* Left: Insight Text */}
            <div>
              <p className="text-base sm:text-lg text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
                {snapshot.insight}
              </p>

              {/* Tags */}
              <div className="flex flex-wrap gap-2 mb-4">
                {snapshot.tags.map((tag, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>

            {/* Right: Mini Chart */}
            <div className="flex flex-col items-center justify-center bg-white/50 dark:bg-slate-900/30 rounded-xl p-4 border border-indigo-200 dark:border-indigo-800/50 min-w-[200px]">
              <div className="text-xs font-medium text-slate-600 dark:text-slate-400 mb-3 uppercase tracking-wide">
                Download Comparison
              </div>
              <div className="flex items-end gap-4 h-24">
                {snapshot.chartData.map((item, index) => (
                  <div key={index} className="flex flex-col items-center gap-2">
                    <div
                      className={`w-16 rounded-t-lg transition-all ${
                        index === 0
                          ? "bg-slate-300 dark:bg-slate-700"
                          : "bg-gradient-to-t from-indigo-500 to-purple-500"
                      }`}
                      style={{ height: `${item.value}%` }}
                    />
                    <span className="text-xs font-medium text-slate-600 dark:text-slate-400">
                      {item.label}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 mt-6 pt-4 border-t border-indigo-200 dark:border-indigo-800/50">
            <div className="text-xs text-slate-600 dark:text-slate-400">
              Generated by AppCortex AI at {snapshot.generatedAt} UTC
            </div>
            <div className="text-xs font-medium text-indigo-600 dark:text-indigo-400">
              ⏱️ Next update in ~2 hours
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

