// app/insights/[slug]/page.tsx

import { getInsights } from "@/lib/insightsApi";
import { Card, Section, Badge } from "@/components/ui";
import Link from "next/link";

interface InsightDetailPageProps {
  params: { slug: string };
}

export default async function InsightDetailPage({ params }: InsightDetailPageProps) {
  const { items } = await getInsights();
  const insight = items.find((i) => i.slug === params.slug);

  if (!insight) {
    return (
      <div className="animate-fade-up py-10">
        <h1 className="text-2xl font-semibold text-slate-50">
          Insight not found
        </h1>
        <p className="mt-2 text-sm text-slate-300">
          We couldn&apos;t find an insight with slug &quot;{params.slug}&quot;.
        </p>
        <Link
          href="/insights"
          className="mt-4 inline-flex items-center text-sm text-cyan-400 hover:text-cyan-300"
        >
          ← Back to insights
        </Link>
      </div>
    );
  }

  const date = new Date(insight.publishedAt).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const badgeVariant =
    insight.category === "Market Trend"
      ? "cyan"
      : insight.category === "Category Report"
      ? "emerald"
      : "amber";

  return (
    <div className="animate-fade-up space-y-6 pb-10">
      {/* Breadcrumb */}
      <div className="text-xs text-slate-400">
        <Link href="/insights" className="hover:text-cyan-400 transition-colors">
          Insights
        </Link>
        <span className="mx-2">/</span>
        <span className="text-slate-300">{insight.title}</span>
      </div>

      {/* Article Header */}
      <Section>
        <div className="space-y-3">
          <div className="flex items-center gap-2">
            <Badge variant={badgeVariant}>{insight.category}</Badge>
            <span className="text-xs text-slate-400">
              {date} · {insight.readingMinutes} min read
            </span>
          </div>

          <h1 className="text-2xl md:text-4xl font-semibold text-slate-50 leading-tight">
            {insight.title}
          </h1>

          <p className="text-base md:text-lg text-slate-300 max-w-3xl">
            {insight.summary}
          </p>

          <div className="flex items-center gap-4 pt-2 text-xs text-slate-400">
            <span>By AppCortex AI</span>
            <span>·</span>
            <span>Published {date}</span>
          </div>
        </div>
      </Section>

      {/* Article Content */}
      <Card className="p-6 md:p-8">
        <article className="prose prose-invert prose-slate max-w-none">
          <div className="space-y-6 text-sm md:text-base text-slate-300 leading-relaxed">
            <h2 className="text-xl md:text-2xl font-semibold text-slate-50 mt-6 mb-4">
              Key Findings
            </h2>
            
            <p>
              This is a detailed analysis generated by the AppCortex intelligence
              engine. In the production version, this content will be dynamically
              generated based on real market data, app performance metrics, and
              AI-driven insights.
            </p>

            <div className="border-l-4 border-cyan-500 pl-4 py-2 my-6 bg-cyan-500/5 rounded-r-lg">
              <p className="text-cyan-200 font-medium">
                💡 Key Insight: {insight.summary}
              </p>
            </div>

            <h3 className="text-lg md:text-xl font-semibold text-slate-50 mt-6 mb-3">
              Market Context
            </h3>

            <p>
              The app market is constantly evolving, with new trends emerging
              across categories and regions. Our analysis combines:
            </p>

            <ul className="space-y-2 list-disc list-inside text-slate-300 my-4">
              <li>Real-time download and ranking data from major app stores</li>
              <li>Category-level performance metrics and trend analysis</li>
              <li>Regional market dynamics and user behavior patterns</li>
              <li>Developer activity and update frequency signals</li>
            </ul>

            <h3 className="text-lg md:text-xl font-semibold text-slate-50 mt-6 mb-3">
              What This Means
            </h3>

            <p>
              For developers and investors tracking this space, these signals
              provide actionable intelligence for product strategy, market timing,
              and competitive positioning.
            </p>

            <div className="grid gap-4 md:grid-cols-2 my-6">
              <div className="border border-slate-700 rounded-xl bg-slate-950/60 p-4">
                <h4 className="text-sm font-semibold text-slate-100 mb-2">
                  For Developers
                </h4>
                <p className="text-xs text-slate-400">
                  Use these insights to identify market gaps, optimize your
                  launch timing, and understand category dynamics.
                </p>
              </div>

              <div className="border border-slate-700 rounded-xl bg-slate-950/60 p-4">
                <h4 className="text-sm font-semibold text-slate-100 mb-2">
                  For Investors
                </h4>
                <p className="text-xs text-slate-400">
                  Track sector momentum, identify emerging opportunities, and
                  validate market assumptions with real data.
                </p>
              </div>
            </div>

            <h3 className="text-lg md:text-xl font-semibold text-slate-50 mt-6 mb-3">
              Looking Ahead
            </h3>

            <p>
              We&apos;ll continue monitoring these trends and update our analysis
              as new data becomes available. Subscribe to AppCortex alerts to stay
              informed about significant market shifts.
            </p>
          </div>
        </article>
      </Card>

      {/* Related Insights */}
      <Section title="More from this category">
        <div className="grid gap-4 md:grid-cols-2">
          {items
            .filter((i) => i.slug !== insight.slug && i.category === insight.category)
            .slice(0, 2)
            .map((relatedInsight) => (
              <Link
                key={relatedInsight.slug}
                href={`/insights/${relatedInsight.slug}`}
                className="block"
              >
                <Card hover className="p-4">
                  <Badge variant={badgeVariant} className="mb-2">
                    {relatedInsight.category}
                  </Badge>
                  <h3 className="text-sm font-semibold text-slate-50">
                    {relatedInsight.title}
                  </h3>
                  <p className="text-xs text-slate-400 mt-2">
                    {relatedInsight.summary}
                  </p>
                </Card>
              </Link>
            ))}
        </div>
      </Section>

      {/* CTA */}
      <Card className="p-6 md:p-8 text-center">
        <h3 className="text-lg md:text-xl font-semibold text-slate-50 mb-2">
          Want deeper insights?
        </h3>
        <p className="text-sm text-slate-300 mb-4 max-w-xl mx-auto">
          Sign up for AppCortex Pro to access full historical data, custom
          alerts, and AI-powered market forecasts.
        </p>
        <div className="flex justify-center gap-3">
          <Link
            href="/pricing"
            className="inline-flex items-center justify-center rounded-full bg-cyan-500 px-5 py-2 text-sm font-medium text-slate-900 hover:bg-cyan-400 transition-colors"
          >
            View pricing
          </Link>
          <Link
            href="/insights"
            className="inline-flex items-center justify-center rounded-full border border-slate-600 px-5 py-2 text-sm text-slate-200 hover:border-cyan-400 hover:text-cyan-200 transition-colors"
          >
            More insights
          </Link>
        </div>
      </Card>
    </div>
  );
}

